apiVersion: v1
kind: Service
metadata:
  name: marketplace-ui
spec:
  type: LoadBalancer
  selector:
    app: marketplace-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http